#==============================================================================
# Hierarchical dofile generated by Conformal LEC
# Version: 21.10-p100 (15-Apr-2021) (64 bit executable)
#------------------------------------------------------------------------------
# For additional reporting on 'not written' modules, see the 'VERBOSE REPORTING'
# section at the end of the hierarchical dofile
#------------------------------------------------------------------------------
# The command 'set module property' sets the instance context for the current
# root module. It is intended only for hierarchical comparison, and should
# not be modified by the user.
#------------------------------------------------------------------------------
# TERMS AND NOTATIONS USED
#------------------------------------------------------------------------------
# Module Instantiation Ratio: Average number of instantiations per matching module
# Wrapper size: #Logic gates enclosing the module's instance, and bounded by key-points
# Periphery size: #Logic gates in the fanin and fanout cone of instance's input and output boundary, and bounded by key-points
# 0: Indicates pin is constant zero
# 1: Indicates pin is constant one
# X: Indicates pin is full DC
# U: Indicates pin is unreachable
# Z: Indicates pin is floating
# KP<--: Indicates pin's fanin is directly connected to key-point (ignores buffers/inverters)
# -->KP: Indicates pin's fanout is directly connected to key-point (ignores buffers/inverters)
# REP: Indicates pin is representative pin
# EQ_REP: <polarity> rep_pinname>: Indicates pin is a member EQ pin with
# 'rep_pinname' specifying the representative, and 'polarity' specifying
# if it is positive or negative equivalent
# = : Indicates that the pins on LHS and RHS are mapped
# + : Indicates positive polarity for pin mapping
# - : Indicates negative polarity for pin mapping
# ? : Indicates unknown polarity for pin mapping
# G: Indicates that the pin belongs to Golden
# R: Indicates that the pin belongs to Revised
# IN: Indicates that the pin is an Input pin
# OUT: Indicates that the pin is an Output pin
# IO: Indicates that the pin is an Inout pin. Polarity of Inout pin is
#     always '?' because of name-only mapping
#==============================================================================

set_system_mode setup
vpxmode
delete set_seq_merge
set_seq_merge /mcs4_core/rom_store0/rom_data_reg[0]  /mcs4_core/rom_store0/rom_data_reg[1] -Golden
set_seq_merge /mcs4_core/rom_store0/rom_data_reg[0]  /mcs4_core/rom_store0/rom_data_reg[2] -Golden
set_seq_merge /mcs4_core/rom_store0/rom_data_reg[0]  /mcs4_core/rom_store0/rom_data_reg[3] -Golden
set_seq_merge /mcs4_core/rom_store0/rom_data_reg[0]  /mcs4_core/rom_store0/rom_data_reg[4] -Golden
set_seq_merge /mcs4_core/rom_store0/rom_data_reg[0]  /mcs4_core/rom_store0/rom_data_reg[5] -Golden
set_seq_merge /mcs4_core/rom_store0/rom_data_reg[0]  /mcs4_core/rom_store0/rom_data_reg[6] -Golden
set_seq_merge /mcs4_core/rom_store0/rom_data_reg[0]  /mcs4_core/rom_store0/rom_data_reg[7] -Golden
set_seq_merge /mcs4_core/rom_store1/rom_data_reg[0]  /mcs4_core/rom_store1/rom_data_reg[1] -Golden
set_seq_merge /mcs4_core/rom_store1/rom_data_reg[0]  /mcs4_core/rom_store1/rom_data_reg[2] -Golden
set_seq_merge /mcs4_core/rom_store1/rom_data_reg[0]  /mcs4_core/rom_store1/rom_data_reg[3] -Golden
set_seq_merge /mcs4_core/rom_store1/rom_data_reg[0]  /mcs4_core/rom_store1/rom_data_reg[4] -Golden
set_seq_merge /mcs4_core/rom_store1/rom_data_reg[0]  /mcs4_core/rom_store1/rom_data_reg[5] -Golden
set_seq_merge /mcs4_core/rom_store1/rom_data_reg[0]  /mcs4_core/rom_store1/rom_data_reg[6] -Golden
set_seq_merge /mcs4_core/rom_store1/rom_data_reg[0]  /mcs4_core/rom_store1/rom_data_reg[7] -Golden
set_seq_merge /mcs4_core/rom_0_timing_recovery_a11_reg  /mcs4_core/rom_1_timing_recovery_a11_reg -Golden
set_seq_merge /mcs4_core/rom_0_timing_recovery_a12_reg  /mcs4_core/rom_1_timing_recovery_a12_reg -Golden
set_seq_merge /mcs4_core/rom_0_timing_recovery_a21_reg  /mcs4_core/rom_1_timing_recovery_a21_reg -Golden
set_seq_merge /mcs4_core/rom_0_timing_recovery_a22_reg  /mcs4_core/rom_1_timing_recovery_a22_reg -Golden
set_seq_merge /mcs4_core/rom_0_timing_recovery_a31_reg  /mcs4_core/rom_1_timing_recovery_a31_reg -Golden
set_seq_merge /mcs4_core/rom_0_timing_recovery_a32_reg  /mcs4_core/rom_1_timing_recovery_a32_reg -Golden
set_seq_merge /mcs4_core/rom_0_timing_recovery_m11_reg  /mcs4_core/rom_1_timing_recovery_m11_reg -Golden
set_seq_merge /mcs4_core/rom_0_timing_recovery_m12_reg  /mcs4_core/rom_1_timing_recovery_m12_reg -Golden
set_seq_merge /mcs4_core/rom_0_timing_recovery_m21_reg  /mcs4_core/rom_1_timing_recovery_m21_reg -Golden
set_seq_merge /mcs4_core/rom_0_timing_recovery_m22_reg  /mcs4_core/rom_1_timing_recovery_m22_reg -Golden
set_seq_merge /mcs4_core/rom_0_timing_recovery_x11_reg  /mcs4_core/rom_1_timing_recovery_x11_reg -Golden
set_seq_merge /mcs4_core/rom_0_timing_recovery_x12_reg  /mcs4_core/rom_1_timing_recovery_x12_reg -Golden
set_seq_merge /mcs4_core/rom_0_timing_recovery_x21_reg  /mcs4_core/rom_1_timing_recovery_x21_reg -Golden
set_seq_merge /mcs4_core/rom_0_timing_recovery_x22_reg  /mcs4_core/rom_1_timing_recovery_x22_reg -Golden
tclmode
# Root Modules
# Comparing
#-------------------------------------------------------------------------------
# MODULE mcs4_pad_frame (G) INSTANCE / (G)
# MODULE mcs4_pad_frame (R) INSTANCE / (R)
# Wrapper size: (G) = 0  (R) = 0
# Periphery size: (G) = 0  (R) = 0
#-------------------------------------------------------------------------------
# RESOLVED Constraints
# IN (G) sysclk (REP)  =   (R) sysclk (REP) (by name)
# IN (G) poc_pad (REP)  =   (R) poc_pad (REP) (by name)
# IN (G) clear_pad (REP)  =   (R) clear_pad (REP) (by name)
# RESOLVED Constraints
# OUT (G) p_out[9] (REP)  =   (R) p_out[9] (REP) (by name)
# OUT (G) p_out[8] (REP)  =   (R) p_out[8] (REP) (by name)
# OUT (G) p_out[7] (REP)  =   (R) p_out[7] (REP) (by name)
# OUT (G) p_out[6] (REP)  =   (R) p_out[6] (REP) (by name)
# OUT (G) p_out[5] (REP)  =   (R) p_out[5] (REP) (by name)
# OUT (G) p_out[4] (REP)  =   (R) p_out[4] (REP) (by name)
# OUT (G) p_out[3] (REP)  =   (R) p_out[3] (REP) (by name)
# OUT (G) p_out[2] (REP)  =   (R) p_out[2] (REP) (by name)
# OUT (G) p_out[1] (REP)  =   (R) p_out[1] (REP) (by name)
# OUT (G) p_out[0] (REP)  =   (R) p_out[0] (REP) (by name)
# OUT (G) io_pad[7] (REP)  =   (R) io_pad[7] (REP) (by name)
# OUT (G) io_pad[6] (REP)  =   (R) io_pad[6] (REP) (by name)
# OUT (G) io_pad[5] (REP)  =   (R) io_pad[5] (REP) (by name)
# OUT (G) io_pad[4] (REP)  =   (R) io_pad[4] (REP) (by name)
# OUT (G) io_pad[3] (REP)  =   (R) io_pad[3] (REP) (by name)
# OUT (G) io_pad[2] (REP)  =   (R) io_pad[2] (REP) (by name)
# OUT (G) io_pad[1] (REP)  =   (R) io_pad[1] (REP) (by name)
# OUT (G) io_pad[0] (REP)  =   (R) io_pad[0] (REP) (by name)
# RESOLVED Constraints
# IO (G) VDD (REP)  =   (R) VDD (REP) (by name)
# IO (G) VSS (REP)  =   (R) VSS (REP) (by name)
# IO (G) VDD_IOR (REP)  =   (R) VDD_IOR (REP) (by name)
# IO (G) VSS_IOR (REP)  =   (R) VSS_IOR (REP) (by name)
set_root_module mcs4_pad_frame -Golden
set_root_module mcs4_pad_frame -Revised
set_module_property -instance / -Golden
set_module_property -instance / -Revised
report_black_box -NOHidden
set_system_mode lec
report_design_data; report_unmapped_points -summary; report_unmapped_points -notmapped; analyze_datapath -module -verbose; eval analyze_datapath -flowgraph -verbose
add_compared_points -all
compare
save_hier_compare_result
set_system_mode setup
usage
report_hier_compare_result
report_hier_compare_result -Nonequivalent
report_hier_compare_result -Abort
report_hier_compare_result -Uncompared
#-------------------------------------------------------------------------------
# VERBOSE REPORTING
#-------------------------------------------------------------------------------
# The following modules are not written  because they have been added as black box:
# PADVDD (G)
# PADVSS (G)
# PADVDDIOR (G)
# PADVSSIOR (G)
# padIORINGCORNER (G)
# PADVDD (R)
# PADVDDIOR (R)
# PADVSS (R)
# PADVSSIOR (R)
#-------------------------------------------------------------------------------
# The following Golden modules are not written because of non-matching
# instance names in Revised:
# scratchpad (Instance: mcs4_core/i4004/sp_board) (G)
# instruction_decode (Instance: mcs4_core/i4004/id_board) (G)
# i4001_ROM_NUMBER0_IO_OUTPUT15 (Instance: mcs4_core/rom_0) (G)
# i4001_ROM_NUMBER1_IO_OUTPUT15 (Instance: mcs4_core/rom_1) (G)
# mcs4 (Instance: mcs4_core) (G)
# i4002_ram_RAM_ARRAY_SIZE32 (Instance: mcs4_core/ram_0/ram0) (G)
# i4001_rom_ROM_NUMBER0 (Instance: mcs4_core/rom_store0) (G)
# timing_io (Instance: mcs4_core/i4004/tio_board) (G)
# i4004 (Instance: mcs4_core/i4004) (G)
# i4001_rom_ROM_NUMBER1 (Instance: mcs4_core/rom_store1) (G)
# i4002 (Instance: mcs4_core/ram_0) (G)
# instruction_pointer (Instance: mcs4_core/i4004/ip_board) (G)
# alu (Instance: mcs4_core/i4004/alu_board) (G)
# i4003 (Instance: mcs4_core/shiftreg) (G)
#-------------------------------------------------------------------------------
# _END_OF_LEC_HIERARCHICAL_DOFILE_
