
//input ports
add mapped point sysclk sysclk -type PI PI
add mapped point poc_pad poc_pad -type PI PI
add mapped point clear_pad clear_pad -type PI PI

//output ports
add mapped point p_out[9] p_out[9] -type PO PO
add mapped point p_out[8] p_out[8] -type PO PO
add mapped point p_out[7] p_out[7] -type PO PO
add mapped point p_out[6] p_out[6] -type PO PO
add mapped point p_out[5] p_out[5] -type PO PO
add mapped point p_out[4] p_out[4] -type PO PO
add mapped point p_out[3] p_out[3] -type PO PO
add mapped point p_out[2] p_out[2] -type PO PO
add mapped point p_out[1] p_out[1] -type PO PO
add mapped point p_out[0] p_out[0] -type PO PO

//inout ports
add mapped point io_pad[7] io_pad[7]
add mapped point io_pad[6] io_pad[6]
add mapped point io_pad[5] io_pad[5]
add mapped point io_pad[4] io_pad[4]
add mapped point io_pad[3] io_pad[3]
add mapped point io_pad[2] io_pad[2]
add mapped point io_pad[1] io_pad[1]
add mapped point io_pad[0] io_pad[0]




//Sequential Pins
add mapped point ram_0/src_ram_sel/q ram_0_src_ram_sel_reg/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[19][1]/q ram_0_ram1_ram_array_reg[19][1]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[19][0]/q ram_0_ram1_ram_array_reg[19][0]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[18][2]/q ram_0_ram0_ram_array_reg[18][2]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[18][3]/q ram_0_ram0_ram_array_reg[18][3]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[18][1]/q ram_0_ram0_ram_array_reg[18][1]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[18][0]/q ram_0_ram0_ram_array_reg[18][0]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[16][3]/q ram_0_ram0_ram_array_reg[16][3]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[16][2]/q ram_0_ram0_ram_array_reg[16][2]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[16][1]/q ram_0_ram0_ram_array_reg[16][1]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[16][0]/q ram_0_ram0_ram_array_reg[16][0]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[18][3]/q ram_0_ram2_ram_array_reg[18][3]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[18][2]/q ram_0_ram2_ram_array_reg[18][2]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[18][1]/q ram_0_ram2_ram_array_reg[18][1]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[18][0]/q ram_0_ram2_ram_array_reg[18][0]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[16][3]/q ram_0_ram2_ram_array_reg[16][3]/Q  -type DFF DFF
add mapped point ram_0/char_num[0]/q ram_0_char_num_reg[0]/Q  -type DFF DFF
add mapped point ram_0/char_num[1]/q ram_0_char_num_reg[1]/Q  -type DFF DFF
add mapped point ram_0/char_num[2]/q ram_0_char_num_reg[2]/Q  -type DFF DFF
add mapped point ram_0/char_num[3]/q ram_0_char_num_reg[3]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[16][2]/q ram_0_ram2_ram_array_reg[16][2]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[16][1]/q ram_0_ram2_ram_array_reg[16][1]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[16][0]/q ram_0_ram2_ram_array_reg[16][0]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[6][3]/q ram_0_ram1_ram_array_reg[6][3]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[6][2]/q ram_0_ram1_ram_array_reg[6][2]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[6][1]/q ram_0_ram1_ram_array_reg[6][1]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[6][0]/q ram_0_ram1_ram_array_reg[6][0]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[6][3]/q ram_0_ram3_ram_array_reg[6][3]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[6][0]/q ram_0_ram3_ram_array_reg[6][0]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[6][2]/q ram_0_ram3_ram_array_reg[6][2]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[6][1]/q ram_0_ram3_ram_array_reg[6][1]/Q  -type DFF DFF
add mapped point i4004/alu_board/n0750/q i4004_alu_board_n0750_reg/Q  -type DFF DFF
add mapped point i4004/alu_board/n0751/q i4004_alu_board_n0751_reg/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[8][0]/q ram_0_ram1_ram_array_reg[8][0]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[2][3]/q ram_0_ram1_ram_array_reg[2][3]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[2][2]/q ram_0_ram1_ram_array_reg[2][2]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[2][1]/q ram_0_ram1_ram_array_reg[2][1]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[2][0]/q ram_0_ram1_ram_array_reg[2][0]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[0][3]/q ram_0_ram1_ram_array_reg[0][3]/Q  -type DFF DFF
add mapped point i4004/alu_board/n0749/q i4004_alu_board_n0749_reg/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[0][2]/q ram_0_ram1_ram_array_reg[0][2]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[0][1]/q ram_0_ram1_ram_array_reg[0][1]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[0][0]/q ram_0_ram1_ram_array_reg[0][0]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[2][3]/q ram_0_ram3_ram_array_reg[2][3]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[2][2]/q ram_0_ram3_ram_array_reg[2][2]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[2][1]/q ram_0_ram3_ram_array_reg[2][1]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[2][0]/q ram_0_ram3_ram_array_reg[2][0]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[0][3]/q ram_0_ram3_ram_array_reg[0][3]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[0][2]/q ram_0_ram3_ram_array_reg[0][2]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[0][1]/q ram_0_ram3_ram_array_reg[0][1]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[0][0]/q ram_0_ram3_ram_array_reg[0][0]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[15][1]/q ram_0_ram1_ram_array_reg[15][1]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[15][3]/q ram_0_ram1_ram_array_reg[15][3]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[15][2]/q ram_0_ram1_ram_array_reg[15][2]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[15][0]/q ram_0_ram1_ram_array_reg[15][0]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[15][3]/q ram_0_ram3_ram_array_reg[15][3]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[15][2]/q ram_0_ram3_ram_array_reg[15][2]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[15][1]/q ram_0_ram3_ram_array_reg[15][1]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[15][0]/q ram_0_ram3_ram_array_reg[15][0]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[11][3]/q ram_0_ram1_ram_array_reg[11][3]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[11][2]/q ram_0_ram1_ram_array_reg[11][2]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[11][1]/q ram_0_ram1_ram_array_reg[11][1]/Q  -type DFF DFF
add mapped point ram_0/oport[0]/q ram_0_oport_reg[0]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[11][0]/q ram_0_ram1_ram_array_reg[11][0]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[9][2]/q ram_0_ram1_ram_array_reg[9][2]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[9][3]/q ram_0_ram1_ram_array_reg[9][3]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[9][1]/q ram_0_ram1_ram_array_reg[9][1]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[9][0]/q ram_0_ram1_ram_array_reg[9][0]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[11][2]/q ram_0_ram3_ram_array_reg[11][2]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[11][3]/q ram_0_ram3_ram_array_reg[11][3]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[11][1]/q ram_0_ram3_ram_array_reg[11][1]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[11][0]/q ram_0_ram3_ram_array_reg[11][0]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[9][2]/q ram_0_ram3_ram_array_reg[9][2]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[9][3]/q ram_0_ram3_ram_array_reg[9][3]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[9][1]/q ram_0_ram3_ram_array_reg[9][1]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[9][0]/q ram_0_ram3_ram_array_reg[9][0]/Q  -type DFF DFF
add mapped point i4004/id_board/n0805/q i4004_id_board_n0805_reg/Q  -type DFF DFF
add mapped point i4004/id_board/n0801/q i4004_id_board_n0801_reg/Q  -type DFF DFF
add mapped point i4004/id_board/n0797/q i4004_id_board_n0797_reg/Q  -type DFF DFF
add mapped point i4004/tio_board/n0699/q i4004_tio_board_n0699_reg/Q  -type DFF DFF
add mapped point i4004/tio_board/data_out[0]/q i4004_tio_board_data_out_reg[0]/Q  -type DFF DFF
add mapped point i4004/tio_board/data_out[3]/q i4004_tio_board_data_out_reg[3]/Q  -type DFF DFF
add mapped point i4004/tio_board/data_out[2]/q i4004_tio_board_data_out_reg[2]/Q  -type DFF DFF
add mapped point i4004/tio_board/data_out[1]/q i4004_tio_board_data_out_reg[1]/Q  -type DFF DFF
add mapped point rom_1/data_out[2]/q rom_1_data_out_reg[2]/Q  -type DFF DFF
add mapped point rom_1/data_out[1]/q rom_1_data_out_reg[1]/Q  -type DFF DFF
add mapped point rom_1/data_out[3]/q rom_1_data_out_reg[3]/Q  -type DFF DFF
add mapped point rom_1/data_out[0]/q rom_1_data_out_reg[0]/Q  -type DFF DFF
add mapped point rom_0/data_out[2]/q rom_0_data_out_reg[2]/Q  -type DFF DFF
add mapped point rom_0/data_out[3]/q rom_0_data_out_reg[3]/Q  -type DFF DFF
add mapped point rom_0/data_out[1]/q rom_0_data_out_reg[1]/Q  -type DFF DFF
add mapped point rom_0/srcff/q rom_0_srcff_reg/Q  -type DFF DFF
add mapped point rom_1/srcff/q rom_1_srcff_reg/Q  -type DFF DFF
add mapped point rom_0/data_out[0]/q rom_0_data_out_reg[0]/Q  -type DFF DFF
add mapped point i4004/ip_board/carry_out/q i4004_ip_board_carry_out_reg/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[7][0]/q i4004_sp_board_dram_array_reg[7][0]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[7][1]/q i4004_sp_board_dram_array_reg[7][1]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[7][2]/q i4004_sp_board_dram_array_reg[7][2]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[7][3]/q i4004_sp_board_dram_array_reg[7][3]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[7][4]/q i4004_sp_board_dram_array_reg[7][4]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[7][5]/q i4004_sp_board_dram_array_reg[7][5]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[7][6]/q i4004_sp_board_dram_array_reg[7][6]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[7][7]/q i4004_sp_board_dram_array_reg[7][7]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[3][0]/q i4004_sp_board_dram_array_reg[3][0]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[3][1]/q i4004_sp_board_dram_array_reg[3][1]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[3][2]/q i4004_sp_board_dram_array_reg[3][2]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[3][3]/q i4004_sp_board_dram_array_reg[3][3]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[3][4]/q i4004_sp_board_dram_array_reg[3][4]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[3][5]/q i4004_sp_board_dram_array_reg[3][5]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[3][6]/q i4004_sp_board_dram_array_reg[3][6]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[3][7]/q i4004_sp_board_dram_array_reg[3][7]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[5][0]/q i4004_sp_board_dram_array_reg[5][0]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[5][1]/q i4004_sp_board_dram_array_reg[5][1]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[5][2]/q i4004_sp_board_dram_array_reg[5][2]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[5][3]/q i4004_sp_board_dram_array_reg[5][3]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[5][4]/q i4004_sp_board_dram_array_reg[5][4]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[5][5]/q i4004_sp_board_dram_array_reg[5][5]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[5][6]/q i4004_sp_board_dram_array_reg[5][6]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[5][7]/q i4004_sp_board_dram_array_reg[5][7]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[6][2]/q i4004_sp_board_dram_array_reg[6][2]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[6][3]/q i4004_sp_board_dram_array_reg[6][3]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[6][4]/q i4004_sp_board_dram_array_reg[6][4]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[6][5]/q i4004_sp_board_dram_array_reg[6][5]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[6][7]/q i4004_sp_board_dram_array_reg[6][7]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[6][0]/q i4004_sp_board_dram_array_reg[6][0]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[6][6]/q i4004_sp_board_dram_array_reg[6][6]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[6][1]/q i4004_sp_board_dram_array_reg[6][1]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_array[1][0]/q i4004_ip_board_dram_array_reg[1][0]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_array[1][1]/q i4004_ip_board_dram_array_reg[1][1]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_array[1][2]/q i4004_ip_board_dram_array_reg[1][2]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_array[1][3]/q i4004_ip_board_dram_array_reg[1][3]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_array[1][4]/q i4004_ip_board_dram_array_reg[1][4]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_array[1][5]/q i4004_ip_board_dram_array_reg[1][5]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_array[1][6]/q i4004_ip_board_dram_array_reg[1][6]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_array[1][7]/q i4004_ip_board_dram_array_reg[1][7]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_array[1][8]/q i4004_ip_board_dram_array_reg[1][8]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_array[1][9]/q i4004_ip_board_dram_array_reg[1][9]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_array[1][10]/q i4004_ip_board_dram_array_reg[1][10]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_array[1][11]/q i4004_ip_board_dram_array_reg[1][11]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_array[2][0]/q i4004_ip_board_dram_array_reg[2][0]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_array[2][1]/q i4004_ip_board_dram_array_reg[2][1]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_array[2][2]/q i4004_ip_board_dram_array_reg[2][2]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_array[2][3]/q i4004_ip_board_dram_array_reg[2][3]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_array[2][4]/q i4004_ip_board_dram_array_reg[2][4]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_array[2][5]/q i4004_ip_board_dram_array_reg[2][5]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_array[2][6]/q i4004_ip_board_dram_array_reg[2][6]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_array[2][7]/q i4004_ip_board_dram_array_reg[2][7]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_array[2][8]/q i4004_ip_board_dram_array_reg[2][8]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_array[2][9]/q i4004_ip_board_dram_array_reg[2][9]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_array[2][10]/q i4004_ip_board_dram_array_reg[2][10]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_array[2][11]/q i4004_ip_board_dram_array_reg[2][11]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[12][3]/q ram_0_ram1_ram_array_reg[12][3]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[12][2]/q ram_0_ram1_ram_array_reg[12][2]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[12][1]/q ram_0_ram1_ram_array_reg[12][1]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[12][0]/q ram_0_ram1_ram_array_reg[12][0]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[8][0]/q ram_0_ram3_ram_array_reg[8][0]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[8][1]/q ram_0_ram3_ram_array_reg[8][1]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[8][2]/q ram_0_ram3_ram_array_reg[8][2]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[8][3]/q ram_0_ram3_ram_array_reg[8][3]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[10][0]/q ram_0_ram3_ram_array_reg[10][0]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[10][1]/q ram_0_ram3_ram_array_reg[10][1]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[10][2]/q ram_0_ram3_ram_array_reg[10][2]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[10][3]/q ram_0_ram3_ram_array_reg[10][3]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[12][1]/q ram_0_ram3_ram_array_reg[12][1]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[8][1]/q ram_0_ram1_ram_array_reg[8][1]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[8][2]/q ram_0_ram1_ram_array_reg[8][2]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[8][3]/q ram_0_ram1_ram_array_reg[8][3]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[10][0]/q ram_0_ram1_ram_array_reg[10][0]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[10][1]/q ram_0_ram1_ram_array_reg[10][1]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[10][2]/q ram_0_ram1_ram_array_reg[10][2]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[10][3]/q ram_0_ram1_ram_array_reg[10][3]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[14][0]/q ram_0_ram3_ram_array_reg[14][0]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[14][1]/q ram_0_ram3_ram_array_reg[14][1]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[14][2]/q ram_0_ram3_ram_array_reg[14][2]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[14][3]/q ram_0_ram3_ram_array_reg[14][3]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[14][0]/q ram_0_ram1_ram_array_reg[14][0]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[14][1]/q ram_0_ram1_ram_array_reg[14][1]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[14][2]/q ram_0_ram1_ram_array_reg[14][2]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[14][3]/q ram_0_ram1_ram_array_reg[14][3]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[12][3]/q ram_0_ram3_ram_array_reg[12][3]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[12][2]/q ram_0_ram3_ram_array_reg[12][2]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[12][0]/q ram_0_ram3_ram_array_reg[12][0]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[14][3]/q ram_0_ram0_ram_array_reg[14][3]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[16][0]/q ram_0_ram3_ram_array_reg[16][0]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[16][1]/q ram_0_ram3_ram_array_reg[16][1]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[16][2]/q ram_0_ram3_ram_array_reg[16][2]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[16][3]/q ram_0_ram3_ram_array_reg[16][3]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[18][0]/q ram_0_ram3_ram_array_reg[18][0]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[18][1]/q ram_0_ram3_ram_array_reg[18][1]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[18][2]/q ram_0_ram3_ram_array_reg[18][2]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[18][3]/q ram_0_ram3_ram_array_reg[18][3]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[16][0]/q ram_0_ram1_ram_array_reg[16][0]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[16][1]/q ram_0_ram1_ram_array_reg[16][1]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[16][2]/q ram_0_ram1_ram_array_reg[16][2]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[16][3]/q ram_0_ram1_ram_array_reg[16][3]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[18][0]/q ram_0_ram1_ram_array_reg[18][0]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[18][1]/q ram_0_ram1_ram_array_reg[18][1]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[18][2]/q ram_0_ram1_ram_array_reg[18][2]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[18][3]/q ram_0_ram1_ram_array_reg[18][3]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_array[3][0]/q i4004_ip_board_dram_array_reg[3][0]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_array[3][1]/q i4004_ip_board_dram_array_reg[3][1]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_array[3][2]/q i4004_ip_board_dram_array_reg[3][2]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_array[3][3]/q i4004_ip_board_dram_array_reg[3][3]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_array[3][4]/q i4004_ip_board_dram_array_reg[3][4]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_array[3][5]/q i4004_ip_board_dram_array_reg[3][5]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_array[3][7]/q i4004_ip_board_dram_array_reg[3][7]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_array[3][8]/q i4004_ip_board_dram_array_reg[3][8]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_array[3][9]/q i4004_ip_board_dram_array_reg[3][9]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_array[3][10]/q i4004_ip_board_dram_array_reg[3][10]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_array[3][11]/q i4004_ip_board_dram_array_reg[3][11]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_array[3][6]/q i4004_ip_board_dram_array_reg[3][6]/Q  -type DFF DFF
add mapped point i4004/ip_board/n0517/q i4004_ip_board_n0517_reg/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[8][0]/q ram_0_ram2_ram_array_reg[8][0]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[8][1]/q ram_0_ram2_ram_array_reg[8][1]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[8][2]/q ram_0_ram2_ram_array_reg[8][2]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[8][3]/q ram_0_ram2_ram_array_reg[8][3]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[10][0]/q ram_0_ram2_ram_array_reg[10][0]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[10][1]/q ram_0_ram2_ram_array_reg[10][1]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[10][2]/q ram_0_ram2_ram_array_reg[10][2]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[10][3]/q ram_0_ram2_ram_array_reg[10][3]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[8][0]/q ram_0_ram0_ram_array_reg[8][0]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[8][1]/q ram_0_ram0_ram_array_reg[8][1]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[8][2]/q ram_0_ram0_ram_array_reg[8][2]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[8][3]/q ram_0_ram0_ram_array_reg[8][3]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[10][0]/q ram_0_ram0_ram_array_reg[10][0]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[10][1]/q ram_0_ram0_ram_array_reg[10][1]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[10][2]/q ram_0_ram0_ram_array_reg[10][2]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[10][3]/q ram_0_ram0_ram_array_reg[10][3]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[14][0]/q ram_0_ram2_ram_array_reg[14][0]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[14][1]/q ram_0_ram2_ram_array_reg[14][1]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[14][2]/q ram_0_ram2_ram_array_reg[14][2]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[14][3]/q ram_0_ram2_ram_array_reg[14][3]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[14][0]/q ram_0_ram0_ram_array_reg[14][0]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[14][1]/q ram_0_ram0_ram_array_reg[14][1]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[14][2]/q ram_0_ram0_ram_array_reg[14][2]/Q  -type DFF DFF
add mapped point i4004/tio_board/timing_generator/sync/q i4004_tio_board_timing_generator_sync_reg/Q  -type DFF DFF
add mapped point i4004/alu_board/tmp[2]/q i4004_alu_board_tmp_reg[2]/Q  -type DFF DFF
add mapped point i4004/alu_board/tmp[0]/q i4004_alu_board_tmp_reg[0]/Q  -type DFF DFF
add mapped point i4004/alu_board/tmp[3]/q i4004_alu_board_tmp_reg[3]/Q  -type DFF DFF
add mapped point rom_0/chipsel/q rom_0_chipsel_reg/Q  -type DFF DFF
add mapped point i4004/ip_board/addr_rfsh_1/slave/q i4004_ip_board_addr_rfsh_1_slave_reg/Q  -type DFF DFF
add mapped point i4004/ip_board/addr_ptr_1/slave/q i4004_ip_board_addr_ptr_1_slave_reg/Q  -type DFF DFF
add mapped point i4004/sp_board/reg_rfsh_2/slave/q i4004_sp_board_reg_rfsh_2_slave_reg/Q  -type DFF DFF
add mapped point i4004/alu_board/tmp[1]/q i4004_alu_board_tmp_reg[1]/Q  -type DFF DFF
add mapped point i4004/sp_board/din_n[2]/q i4004_sp_board_din_n_reg[2]/Q  -type DFF DFF
add mapped point i4004/sp_board/din_n[3]/q i4004_sp_board_din_n_reg[3]/Q  -type DFF DFF
add mapped point i4004/sp_board/din_n[1]/q i4004_sp_board_din_n_reg[1]/Q  -type DFF DFF
add mapped point i4004/sp_board/din_n[0]/q i4004_sp_board_din_n_reg[0]/Q  -type DFF DFF
add mapped point rom_1/chipsel/q rom_1_chipsel_reg/Q  -type DFF DFF
add mapped point clockgen/clockdiv[1]/q clockgen_clockdiv_reg[1]/Q  -type DFF DFF
add mapped point shiftreg/cp_delay[3]/q shiftreg_cp_delay_reg[3]/Q  -type DFF DFF
add mapped point i4004/alu_board/n0871/q i4004_alu_board_n0871_reg/Q  -type DFF DFF
add mapped point i4004/alu_board/n0870/q i4004_alu_board_n0870_reg/Q  -type DFF DFF
add mapped point i4004/alu_board/n0872/q i4004_alu_board_n0872_reg/Q  -type DFF DFF
add mapped point i4004/alu_board/n0550/q i4004_alu_board_n0550_reg/Q  -type DFF DFF
add mapped point i4004/alu_board/n0893/q i4004_alu_board_n0893_reg/Q  -type DFF DFF
add mapped point i4004/alu_board/n0891/q i4004_alu_board_n0891_reg/Q  -type DFF DFF
add mapped point i4004/alu_board/n0889/q i4004_alu_board_n0889_reg/Q  -type DFF DFF
add mapped point i4004/ip_board/incr_in[3]/q i4004_ip_board_incr_in_reg[3]/Q  -type DFF DFF
add mapped point i4004/alu_board/acc[2]/q i4004_alu_board_acc_reg[2]/Q  -type DFF DFF
add mapped point i4004/ip_board/incr_in[1]/q i4004_ip_board_incr_in_reg[1]/Q  -type DFF DFF
add mapped point i4004/ip_board/incr_in[0]/q i4004_ip_board_incr_in_reg[0]/Q  -type DFF DFF
add mapped point i4004/alu_board/n0887/q i4004_alu_board_n0887_reg/Q  -type DFF DFF
add mapped point clockgen/clockdiv[0]/q clockgen_clockdiv_reg[0]/Q  -type DFF DFF
add mapped point clockgen/clockdiv[0]/q clockgen_clockdiv_reg[0]/QN  -type DFF DFF
add mapped point i4004/alu_board/n0873/q i4004_alu_board_n0873_reg/Q  -type DFF DFF
add mapped point i4004/alu_board/acc[3]/q i4004_alu_board_acc_reg[3]/Q  -type DFF DFF
add mapped point shiftreg/cp_delay[2]/q shiftreg_cp_delay_reg[2]/Q  -type DFF DFF
add mapped point shiftreg/cp_delay[2]/q shiftreg_cp_delay_reg[2]/QN  -type DFF DFF
add mapped point i4004/alu_board/acc[0]/q i4004_alu_board_acc_reg[0]/Q  -type DFF DFF
add mapped point shiftreg/cp_delay[0]/q shiftreg_cp_delay_reg[0]/Q  -type DFF DFF
add mapped point i4004/alu_board/cy/q i4004_alu_board_cy_reg/Q  -type DFF DFF
add mapped point ram_0/opa[3]/q ram_0_opa_reg[3]/Q  -type DFF DFF
add mapped point rom_0/extbusdrive/q rom_0_extbusdrive_reg/Q  -type DFF DFF
add mapped point clockgen/clockdiv[4]/q clockgen_clockdiv_reg[4]/Q  -type DFF DFF
add mapped point clockgen/clockdiv[4]/q clockgen_clockdiv_reg[4]/QN  -type DFF DFF
add mapped point i4004/ip_board/incr_in[2]/q i4004_ip_board_incr_in_reg[2]/Q  -type DFF DFF
add mapped point rom_1/extbusdrive/q rom_1_extbusdrive_reg/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_temp[2]/q i4004_ip_board_dram_temp_reg[2]/Q  -type DFF DFF
add mapped point clockgen/clockdiv[3]/q clockgen_clockdiv_reg[3]/Q  -type DFF DFF
add mapped point clockgen/clockdiv[3]/q clockgen_clockdiv_reg[3]/QN  -type DFF DFF
add mapped point ram_0/opa[1]/q ram_0_opa_reg[1]/Q  -type DFF DFF
add mapped point ram_0/opa[1]/q ram_0_opa_reg[1]/QN  -type DFF DFF
add mapped point i4004/ip_board/dram_temp[11]/q i4004_ip_board_dram_temp_reg[11]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_temp[1]/q i4004_ip_board_dram_temp_reg[1]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_temp[5]/q i4004_ip_board_dram_temp_reg[5]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_temp[4]/q i4004_ip_board_dram_temp_reg[4]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_temp[6]/q i4004_ip_board_dram_temp_reg[6]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_temp[8]/q i4004_ip_board_dram_temp_reg[8]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_temp[10]/q i4004_ip_board_dram_temp_reg[10]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_temp[9]/q i4004_ip_board_dram_temp_reg[9]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_temp[3]/q i4004_ip_board_dram_temp_reg[3]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_temp[7]/q i4004_ip_board_dram_temp_reg[7]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_temp[0]/q i4004_ip_board_dram_temp_reg[0]/Q  -type DFF DFF
add mapped point i4004/ip_board/addr_rfsh_0/slave/q i4004_ip_board_addr_rfsh_0_slave_reg/Q  -type DFF DFF
add mapped point i4004/sp_board/reg_rfsh_0/slave/q i4004_sp_board_reg_rfsh_0_slave_reg/Q  -type DFF DFF
add mapped point i4004/ip_board/addr_ptr_0/slave/q i4004_ip_board_addr_ptr_0_slave_reg/Q  -type DFF DFF
add mapped point i4004/sp_board/reg_rfsh_1/slave/q i4004_sp_board_reg_rfsh_1_slave_reg/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_temp[5]/q i4004_sp_board_dram_temp_reg[5]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_temp[6]/q i4004_sp_board_dram_temp_reg[6]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_temp[7]/q i4004_sp_board_dram_temp_reg[7]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_temp[2]/q i4004_sp_board_dram_temp_reg[2]/Q  -type DFF DFF
add mapped point i4004/id_board/opr[2]/q i4004_id_board_opr_reg[2]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_temp[3]/q i4004_sp_board_dram_temp_reg[3]/Q  -type DFF DFF
add mapped point i4004/id_board/opr[3]/q i4004_id_board_opr_reg[3]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_temp[4]/q i4004_sp_board_dram_temp_reg[4]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_temp[1]/q i4004_sp_board_dram_temp_reg[1]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_temp[0]/q i4004_sp_board_dram_temp_reg[0]/Q  -type DFF DFF
add mapped point i4004/id_board/opa[2]/q i4004_id_board_opa_reg[2]/Q  -type DFF DFF
add mapped point clockgen/clk2/q clockgen_clk2_reg/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[19][2]/q ram_0_ram1_ram_array_reg[19][2]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[19][3]/q ram_0_ram1_ram_array_reg[19][3]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[17][0]/q ram_0_ram3_ram_array_reg[17][0]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[17][1]/q ram_0_ram3_ram_array_reg[17][1]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[17][2]/q ram_0_ram3_ram_array_reg[17][2]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[17][3]/q ram_0_ram3_ram_array_reg[17][3]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[19][0]/q ram_0_ram3_ram_array_reg[19][0]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[19][1]/q ram_0_ram3_ram_array_reg[19][1]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[19][2]/q ram_0_ram3_ram_array_reg[19][2]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[19][3]/q ram_0_ram3_ram_array_reg[19][3]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[17][1]/q ram_0_ram1_ram_array_reg[17][1]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[17][2]/q ram_0_ram1_ram_array_reg[17][2]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[17][3]/q ram_0_ram1_ram_array_reg[17][3]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[17][0]/q ram_0_ram1_ram_array_reg[17][0]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_array[0][8]/q i4004_ip_board_dram_array_reg[0][8]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_array[0][9]/q i4004_ip_board_dram_array_reg[0][9]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_array[0][10]/q i4004_ip_board_dram_array_reg[0][10]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_array[0][11]/q i4004_ip_board_dram_array_reg[0][11]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_array[0][7]/q i4004_ip_board_dram_array_reg[0][7]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_array[0][6]/q i4004_ip_board_dram_array_reg[0][6]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_array[0][5]/q i4004_ip_board_dram_array_reg[0][5]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_array[0][1]/q i4004_ip_board_dram_array_reg[0][1]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_array[0][0]/q i4004_ip_board_dram_array_reg[0][0]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_array[0][2]/q i4004_ip_board_dram_array_reg[0][2]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_array[0][3]/q i4004_ip_board_dram_array_reg[0][3]/Q  -type DFF DFF
add mapped point i4004/ip_board/dram_array[0][4]/q i4004_ip_board_dram_array_reg[0][4]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[9][0]/q ram_0_ram2_ram_array_reg[9][0]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[9][1]/q ram_0_ram2_ram_array_reg[9][1]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[9][2]/q ram_0_ram2_ram_array_reg[9][2]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[9][3]/q ram_0_ram2_ram_array_reg[9][3]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[11][0]/q ram_0_ram2_ram_array_reg[11][0]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[11][1]/q ram_0_ram2_ram_array_reg[11][1]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[11][2]/q ram_0_ram2_ram_array_reg[11][2]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[11][3]/q ram_0_ram2_ram_array_reg[11][3]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[9][0]/q ram_0_ram0_ram_array_reg[9][0]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[9][1]/q ram_0_ram0_ram_array_reg[9][1]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[9][2]/q ram_0_ram0_ram_array_reg[9][2]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[9][3]/q ram_0_ram0_ram_array_reg[9][3]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[11][0]/q ram_0_ram0_ram_array_reg[11][0]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[11][1]/q ram_0_ram0_ram_array_reg[11][1]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[11][2]/q ram_0_ram0_ram_array_reg[11][2]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[11][3]/q ram_0_ram0_ram_array_reg[11][3]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[12][0]/q ram_0_ram2_ram_array_reg[12][0]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[12][1]/q ram_0_ram2_ram_array_reg[12][1]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[12][2]/q ram_0_ram2_ram_array_reg[12][2]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[12][3]/q ram_0_ram2_ram_array_reg[12][3]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[12][0]/q ram_0_ram0_ram_array_reg[12][0]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[12][1]/q ram_0_ram0_ram_array_reg[12][1]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[12][2]/q ram_0_ram0_ram_array_reg[12][2]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[12][3]/q ram_0_ram0_ram_array_reg[12][3]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[15][0]/q ram_0_ram2_ram_array_reg[15][0]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[15][1]/q ram_0_ram2_ram_array_reg[15][1]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[15][2]/q ram_0_ram2_ram_array_reg[15][2]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[15][3]/q ram_0_ram2_ram_array_reg[15][3]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[15][1]/q ram_0_ram0_ram_array_reg[15][1]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[15][2]/q ram_0_ram0_ram_array_reg[15][2]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[15][3]/q ram_0_ram0_ram_array_reg[15][3]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[15][0]/q ram_0_ram0_ram_array_reg[15][0]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[13][0]/q ram_0_ram3_ram_array_reg[13][0]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[13][2]/q ram_0_ram3_ram_array_reg[13][2]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[13][1]/q ram_0_ram3_ram_array_reg[13][1]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[13][3]/q ram_0_ram3_ram_array_reg[13][3]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[13][0]/q ram_0_ram1_ram_array_reg[13][0]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[13][1]/q ram_0_ram1_ram_array_reg[13][1]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[13][2]/q ram_0_ram1_ram_array_reg[13][2]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[13][3]/q ram_0_ram1_ram_array_reg[13][3]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[0][0]/q ram_0_ram2_ram_array_reg[0][0]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[0][1]/q ram_0_ram2_ram_array_reg[0][1]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[0][2]/q ram_0_ram2_ram_array_reg[0][2]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[0][3]/q ram_0_ram2_ram_array_reg[0][3]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[1][0]/q ram_0_ram2_ram_array_reg[1][0]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[1][1]/q ram_0_ram2_ram_array_reg[1][1]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[1][2]/q ram_0_ram2_ram_array_reg[1][2]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[1][3]/q ram_0_ram2_ram_array_reg[1][3]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[2][0]/q ram_0_ram2_ram_array_reg[2][0]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[2][1]/q ram_0_ram2_ram_array_reg[2][1]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[2][2]/q ram_0_ram2_ram_array_reg[2][2]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[2][3]/q ram_0_ram2_ram_array_reg[2][3]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[3][0]/q ram_0_ram2_ram_array_reg[3][0]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[3][1]/q ram_0_ram2_ram_array_reg[3][1]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[3][2]/q ram_0_ram2_ram_array_reg[3][2]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[3][3]/q ram_0_ram2_ram_array_reg[3][3]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[4][0]/q ram_0_ram2_ram_array_reg[4][0]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[4][1]/q ram_0_ram2_ram_array_reg[4][1]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[4][2]/q ram_0_ram2_ram_array_reg[4][2]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[4][3]/q ram_0_ram2_ram_array_reg[4][3]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[5][0]/q ram_0_ram2_ram_array_reg[5][0]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[5][1]/q ram_0_ram2_ram_array_reg[5][1]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[5][2]/q ram_0_ram2_ram_array_reg[5][2]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[5][3]/q ram_0_ram2_ram_array_reg[5][3]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[6][0]/q ram_0_ram2_ram_array_reg[6][0]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[6][1]/q ram_0_ram2_ram_array_reg[6][1]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[6][2]/q ram_0_ram2_ram_array_reg[6][2]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[6][3]/q ram_0_ram2_ram_array_reg[6][3]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[7][0]/q ram_0_ram2_ram_array_reg[7][0]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[7][1]/q ram_0_ram2_ram_array_reg[7][1]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[7][2]/q ram_0_ram2_ram_array_reg[7][2]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[7][3]/q ram_0_ram2_ram_array_reg[7][3]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[13][0]/q ram_0_ram2_ram_array_reg[13][0]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[13][1]/q ram_0_ram2_ram_array_reg[13][1]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[13][2]/q ram_0_ram2_ram_array_reg[13][2]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[13][3]/q ram_0_ram2_ram_array_reg[13][3]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[17][0]/q ram_0_ram2_ram_array_reg[17][0]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[17][1]/q ram_0_ram2_ram_array_reg[17][1]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[17][3]/q ram_0_ram2_ram_array_reg[17][3]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[17][2]/q ram_0_ram2_ram_array_reg[17][2]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[19][0]/q ram_0_ram2_ram_array_reg[19][0]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[19][1]/q ram_0_ram2_ram_array_reg[19][1]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[19][2]/q ram_0_ram2_ram_array_reg[19][2]/Q  -type DFF DFF
add mapped point ram_0/ram2/ram_array[19][3]/q ram_0_ram2_ram_array_reg[19][3]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[1][0]/q ram_0_ram3_ram_array_reg[1][0]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[1][1]/q ram_0_ram3_ram_array_reg[1][1]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[1][2]/q ram_0_ram3_ram_array_reg[1][2]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[1][3]/q ram_0_ram3_ram_array_reg[1][3]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[3][0]/q ram_0_ram3_ram_array_reg[3][0]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[3][1]/q ram_0_ram3_ram_array_reg[3][1]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[3][2]/q ram_0_ram3_ram_array_reg[3][2]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[3][3]/q ram_0_ram3_ram_array_reg[3][3]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[4][0]/q ram_0_ram3_ram_array_reg[4][0]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[4][1]/q ram_0_ram3_ram_array_reg[4][1]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[4][2]/q ram_0_ram3_ram_array_reg[4][2]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[5][1]/q ram_0_ram3_ram_array_reg[5][1]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[5][2]/q ram_0_ram3_ram_array_reg[5][2]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[5][3]/q ram_0_ram3_ram_array_reg[5][3]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[4][3]/q ram_0_ram3_ram_array_reg[4][3]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[5][0]/q ram_0_ram3_ram_array_reg[5][0]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[7][0]/q ram_0_ram3_ram_array_reg[7][0]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[7][1]/q ram_0_ram3_ram_array_reg[7][1]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[7][2]/q ram_0_ram3_ram_array_reg[7][2]/Q  -type DFF DFF
add mapped point ram_0/ram3/ram_array[7][3]/q ram_0_ram3_ram_array_reg[7][3]/Q  -type DFF DFF
add mapped point i4004/ip_board/carry_in/q i4004_ip_board_carry_in_reg/Q  -type DFF DFF
add mapped point i4004/ip_board/addr_rfsh_1/master/q i4004_ip_board_addr_rfsh_1_master_reg/Q  -type DFF DFF
add mapped point i4004/ip_board/addr_rfsh_0/master/q i4004_ip_board_addr_rfsh_0_master_reg/Q  -type DFF DFF
add mapped point i4004/ip_board/addr_ptr_1/master/q i4004_ip_board_addr_ptr_1_master_reg/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[7][3]/q ram_0_ram1_ram_array_reg[7][3]/Q  -type DFF DFF
add mapped point ram_0/rfsh_next[0]/q ram_0_rfsh_next_reg[0]/Q  -type DFF DFF
add mapped point ram_0/rfsh_next[1]/q ram_0_rfsh_next_reg[1]/Q  -type DFF DFF
add mapped point ram_0/rfsh_next[2]/q ram_0_rfsh_next_reg[2]/Q  -type DFF DFF
add mapped point ram_0/rfsh_next[4]/q ram_0_rfsh_next_reg[4]/Q  -type DFF DFF
add mapped point ram_0/rfsh_next[3]/q ram_0_rfsh_next_reg[3]/Q  -type DFF DFF
add mapped point ram_0/timing_recovery/a11/q ram_0_timing_recovery_a11_reg/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[7][2]/q ram_0_ram1_ram_array_reg[7][2]/Q  -type DFF DFF
add mapped point ram_0/timing_recovery/a21/q ram_0_timing_recovery_a21_reg/Q  -type DFF DFF
add mapped point ram_0/timing_recovery/a22/q ram_0_timing_recovery_a22_reg/Q  -type DFF DFF
add mapped point ram_0/timing_recovery/a31/q ram_0_timing_recovery_a31_reg/Q  -type DFF DFF
add mapped point ram_0/timing_recovery/a32/q ram_0_timing_recovery_a32_reg/Q  -type DFF DFF
add mapped point ram_0/timing_recovery/m11/q ram_0_timing_recovery_m11_reg/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[7][1]/q ram_0_ram1_ram_array_reg[7][1]/Q  -type DFF DFF
add mapped point ram_0/timing_recovery/m21/q ram_0_timing_recovery_m21_reg/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[7][0]/q ram_0_ram1_ram_array_reg[7][0]/Q  -type DFF DFF
add mapped point ram_0/timing_recovery/x11/q ram_0_timing_recovery_x11_reg/Q  -type DFF DFF
add mapped point ram_0/timing_recovery/x12/q ram_0_timing_recovery_x12_reg/Q  -type DFF DFF
add mapped point ram_0/timing_recovery/x21/q ram_0_timing_recovery_x21_reg/Q  -type DFF DFF
add mapped point i4004/ip_board/addr_ptr_0/master/q i4004_ip_board_addr_ptr_0_master_reg/Q  -type DFF DFF
add mapped point ram_0/timing_recovery/x31/q ram_0_timing_recovery_x31_reg/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[5][3]/q ram_0_ram1_ram_array_reg[5][3]/Q  -type DFF DFF
add mapped point i4004/ip_board/n0416/q i4004_ip_board_n0416_reg/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[5][2]/q ram_0_ram1_ram_array_reg[5][2]/Q  -type DFF DFF
add mapped point i4004/ip_board/n0438/q i4004_ip_board_n0438_reg/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[5][1]/q ram_0_ram1_ram_array_reg[5][1]/Q  -type DFF DFF
add mapped point i4004/ip_board/n0374/q i4004_ip_board_n0374_reg/Q  -type DFF DFF
add mapped point i4004/ip_board/n0384/q i4004_ip_board_n0384_reg/Q  -type DFF DFF
add mapped point rom_0/timing_recovery/a11/q rom_0_timing_recovery_a11_reg/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[5][0]/q ram_0_ram1_ram_array_reg[5][0]/Q  -type DFF DFF
add mapped point rom_0/timing_recovery/a21/q rom_0_timing_recovery_a21_reg/Q  -type DFF DFF
add mapped point rom_0/timing_recovery/a22/q rom_0_timing_recovery_a22_reg/Q  -type DFF DFF
add mapped point rom_0/timing_recovery/a31/q rom_0_timing_recovery_a31_reg/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[4][3]/q ram_0_ram1_ram_array_reg[4][3]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[4][2]/q ram_0_ram1_ram_array_reg[4][2]/Q  -type DFF DFF
add mapped point rom_0/timing_recovery/m12/q rom_0_timing_recovery_m12_reg/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[4][1]/q ram_0_ram1_ram_array_reg[4][1]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[4][0]/q ram_0_ram1_ram_array_reg[4][0]/Q  -type DFF DFF
add mapped point rom_0/timing_recovery/x11/q rom_0_timing_recovery_x11_reg/Q  -type DFF DFF
add mapped point rom_0/timing_recovery/x12/q rom_0_timing_recovery_x12_reg/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[3][3]/q ram_0_ram1_ram_array_reg[3][3]/Q  -type DFF DFF
add mapped point rom_0/timing_recovery/x22/q rom_0_timing_recovery_x22_reg/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[0][2]/q i4004_sp_board_dram_array_reg[0][2]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[0][0]/q i4004_sp_board_dram_array_reg[0][0]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[0][1]/q i4004_sp_board_dram_array_reg[0][1]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[0][3]/q i4004_sp_board_dram_array_reg[0][3]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[3][2]/q ram_0_ram1_ram_array_reg[3][2]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[0][4]/q i4004_sp_board_dram_array_reg[0][4]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[3][1]/q ram_0_ram1_ram_array_reg[3][1]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[0][5]/q i4004_sp_board_dram_array_reg[0][5]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[0][7]/q i4004_sp_board_dram_array_reg[0][7]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[0][6]/q i4004_sp_board_dram_array_reg[0][6]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[1][0]/q i4004_sp_board_dram_array_reg[1][0]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[3][0]/q ram_0_ram1_ram_array_reg[3][0]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[1][3]/q ram_0_ram1_ram_array_reg[1][3]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[1][1]/q i4004_sp_board_dram_array_reg[1][1]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[1][2]/q ram_0_ram1_ram_array_reg[1][2]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[1][1]/q ram_0_ram1_ram_array_reg[1][1]/Q  -type DFF DFF
add mapped point ram_0/ram1/ram_array[1][0]/q ram_0_ram1_ram_array_reg[1][0]/Q  -type DFF DFF
add mapped point i4004/id_board/n0433/q i4004_id_board_n0433_reg/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[1][2]/q i4004_sp_board_dram_array_reg[1][2]/Q  -type DFF DFF
add mapped point i4004/id_board/n0425/q i4004_id_board_n0425_reg/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[19][3]/q ram_0_ram0_ram_array_reg[19][3]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[1][3]/q i4004_sp_board_dram_array_reg[1][3]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[19][2]/q ram_0_ram0_ram_array_reg[19][2]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[19][1]/q ram_0_ram0_ram_array_reg[19][1]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[1][4]/q i4004_sp_board_dram_array_reg[1][4]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[1][5]/q i4004_sp_board_dram_array_reg[1][5]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[1][6]/q i4004_sp_board_dram_array_reg[1][6]/Q  -type DFF DFF
add mapped point shiftreg/shifter[9]/q shiftreg_shifter_reg[9]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[1][7]/q i4004_sp_board_dram_array_reg[1][7]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[2][0]/q i4004_sp_board_dram_array_reg[2][0]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[2][1]/q i4004_sp_board_dram_array_reg[2][1]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[2][2]/q i4004_sp_board_dram_array_reg[2][2]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[2][3]/q i4004_sp_board_dram_array_reg[2][3]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[2][4]/q i4004_sp_board_dram_array_reg[2][4]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[2][5]/q i4004_sp_board_dram_array_reg[2][5]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[2][6]/q i4004_sp_board_dram_array_reg[2][6]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[2][7]/q i4004_sp_board_dram_array_reg[2][7]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[4][0]/q i4004_sp_board_dram_array_reg[4][0]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[4][1]/q i4004_sp_board_dram_array_reg[4][1]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[4][2]/q i4004_sp_board_dram_array_reg[4][2]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[4][3]/q i4004_sp_board_dram_array_reg[4][3]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[19][0]/q ram_0_ram0_ram_array_reg[19][0]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[4][5]/q i4004_sp_board_dram_array_reg[4][5]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[4][6]/q i4004_sp_board_dram_array_reg[4][6]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[4][4]/q i4004_sp_board_dram_array_reg[4][4]/Q  -type DFF DFF
add mapped point i4004/sp_board/dram_array[4][7]/q i4004_sp_board_dram_array_reg[4][7]/Q  -type DFF DFF
add mapped point i4004/id_board/n0405/q i4004_id_board_n0405_reg/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[17][3]/q ram_0_ram0_ram_array_reg[17][3]/Q  -type DFF DFF
add mapped point i4004/sp_board/n0615/q i4004_sp_board_n0615_reg/Q  -type DFF DFF
add mapped point i4004/sp_board/reg_rfsh_0/master/q i4004_sp_board_reg_rfsh_0_master_reg/Q  -type DFF DFF
add mapped point i4004/sp_board/n0592/q i4004_sp_board_n0592_reg/Q  -type DFF DFF
add mapped point i4004/sp_board/reg_rfsh_1/master/q i4004_sp_board_reg_rfsh_1_master_reg/Q  -type DFF DFF
add mapped point i4004/sp_board/reg_rfsh_2/master/q i4004_sp_board_reg_rfsh_2_master_reg/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[17][2]/q ram_0_ram0_ram_array_reg[17][2]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[17][1]/q ram_0_ram0_ram_array_reg[17][1]/Q  -type DFF DFF
add mapped point i4004/tio_board/n0278/q i4004_tio_board_n0278_reg/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[17][0]/q ram_0_ram0_ram_array_reg[17][0]/Q  -type DFF DFF
add mapped point i4004/tio_board/n0707/q i4004_tio_board_n0707_reg/Q  -type DFF DFF
add mapped point i4004/tio_board/timing_generator/a11/q i4004_tio_board_timing_generator_a11_reg/Q  -type DFF DFF
add mapped point i4004/id_board/n0414/q i4004_id_board_n0414_reg/Q  -type DFF DFF
add mapped point i4004/tio_board/timing_generator/a21/q i4004_tio_board_timing_generator_a21_reg/Q  -type DFF DFF
add mapped point i4004/id_board/n0362/q i4004_id_board_n0362_reg/Q  -type DFF DFF
add mapped point i4004/id_board/n0362/q i4004_id_board_n0362_reg/QN  -type DFF DFF
add mapped point i4004/id_board/n0380/q i4004_id_board_n0380_reg/Q  -type DFF DFF
add mapped point i4004/tio_board/timing_generator/m11/q i4004_tio_board_timing_generator_m11_reg/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[13][3]/q ram_0_ram0_ram_array_reg[13][3]/Q  -type DFF DFF
add mapped point i4004/tio_board/timing_generator/a31/q i4004_tio_board_timing_generator_a31_reg/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[13][2]/q ram_0_ram0_ram_array_reg[13][2]/Q  -type DFF DFF
add mapped point i4004/tio_board/timing_generator/m21/q i4004_tio_board_timing_generator_m21_reg/Q  -type DFF DFF
add mapped point i4004/tio_board/timing_generator/x11/q i4004_tio_board_timing_generator_x11_reg/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[13][1]/q ram_0_ram0_ram_array_reg[13][1]/Q  -type DFF DFF
add mapped point i4004/tio_board/timing_generator/x21/q i4004_tio_board_timing_generator_x21_reg/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[13][0]/q ram_0_ram0_ram_array_reg[13][0]/Q  -type DFF DFF
add mapped point i4004/id_board/n0360/q i4004_id_board_n0360_reg/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[2][0]/q ram_0_ram0_ram_array_reg[2][0]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[0][0]/q ram_0_ram0_ram_array_reg[0][0]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[0][1]/q ram_0_ram0_ram_array_reg[0][1]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[0][2]/q ram_0_ram0_ram_array_reg[0][2]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[0][3]/q ram_0_ram0_ram_array_reg[0][3]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[1][0]/q ram_0_ram0_ram_array_reg[1][0]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[1][1]/q ram_0_ram0_ram_array_reg[1][1]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[1][2]/q ram_0_ram0_ram_array_reg[1][2]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[1][3]/q ram_0_ram0_ram_array_reg[1][3]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[2][1]/q ram_0_ram0_ram_array_reg[2][1]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[2][2]/q ram_0_ram0_ram_array_reg[2][2]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[2][3]/q ram_0_ram0_ram_array_reg[2][3]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[3][0]/q ram_0_ram0_ram_array_reg[3][0]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[3][1]/q ram_0_ram0_ram_array_reg[3][1]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[3][2]/q ram_0_ram0_ram_array_reg[3][2]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[3][3]/q ram_0_ram0_ram_array_reg[3][3]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[4][0]/q ram_0_ram0_ram_array_reg[4][0]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[4][1]/q ram_0_ram0_ram_array_reg[4][1]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[4][2]/q ram_0_ram0_ram_array_reg[4][2]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[4][3]/q ram_0_ram0_ram_array_reg[4][3]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[5][0]/q ram_0_ram0_ram_array_reg[5][0]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[5][1]/q ram_0_ram0_ram_array_reg[5][1]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[5][2]/q ram_0_ram0_ram_array_reg[5][2]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[6][0]/q ram_0_ram0_ram_array_reg[6][0]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[6][1]/q ram_0_ram0_ram_array_reg[6][1]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[6][2]/q ram_0_ram0_ram_array_reg[6][2]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[6][3]/q ram_0_ram0_ram_array_reg[6][3]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[7][0]/q ram_0_ram0_ram_array_reg[7][0]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[7][1]/q ram_0_ram0_ram_array_reg[7][1]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[5][3]/q ram_0_ram0_ram_array_reg[5][3]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[7][2]/q ram_0_ram0_ram_array_reg[7][2]/Q  -type DFF DFF
add mapped point ram_0/ram0/ram_array[7][3]/q ram_0_ram0_ram_array_reg[7][3]/Q  -type DFF DFF
add mapped point shiftreg/shifter[1]/q shiftreg_shifter_reg[1]/Q  -type DFF DFF
add mapped point i4004/tio_board/timing_generator/x31/q i4004_tio_board_timing_generator_x31_reg/Q  -type DFF DFF
add mapped point ram_0/timing_recovery/a12/q ram_0_timing_recovery_a12_reg/Q  -type DFF DFF
add mapped point ram_0/timing_recovery/x32/q ram_0_timing_recovery_x32_reg/Q  -type DFF DFF
add mapped point rom_0/n0161/q rom_0_n0161_reg/Q  -type DFF DFF
add mapped point rom_0/timing_recovery/a32/q rom_0_timing_recovery_a32_reg/Q  -type DFF DFF
add mapped point i4004/id_board/n0397/q i4004_id_board_n0397_reg/Q  -type DFF DFF
add mapped point rom_0/timing_recovery/m22/q rom_0_timing_recovery_m22_reg/Q  -type DFF DFF
add mapped point rom_1/n0161/q rom_1_n0161_reg/Q  -type DFF DFF
add mapped point shiftreg/cp_delayed/q shiftreg_cp_delayed_reg/Q  -type DFF DFF
add mapped point i4004/tio_board/n0685/q i4004_tio_board_n0685_reg/Q  -type DFF DFF
add mapped point shiftreg/shifter[0]/q shiftreg_shifter_reg[0]/Q  -type DFF DFF
add mapped point shiftreg/shifter[2]/q shiftreg_shifter_reg[2]/Q  -type DFF DFF
add mapped point shiftreg/shifter[3]/q shiftreg_shifter_reg[3]/Q  -type DFF DFF
add mapped point shiftreg/shifter[4]/q shiftreg_shifter_reg[4]/Q  -type DFF DFF
add mapped point shiftreg/shifter[5]/q shiftreg_shifter_reg[5]/Q  -type DFF DFF
add mapped point shiftreg/shifter[8]/q shiftreg_shifter_reg[8]/Q  -type DFF DFF
add mapped point shiftreg/shifter[7]/q shiftreg_shifter_reg[7]/Q  -type DFF DFF
add mapped point shiftreg/shifter[6]/q shiftreg_shifter_reg[6]/Q  -type DFF DFF
add mapped point ram_0/rfsh_addr[4]/q ram_0_rfsh_addr_reg[4]/Q  -type DFF DFF
add mapped point ram_0/timing_recovery/x22/q ram_0_timing_recovery_x22_reg/Q  -type DFF DFF
add mapped point rom_0/timing_recovery/m11/q rom_0_timing_recovery_m11_reg/Q  -type DFF DFF
add mapped point rom_0/timing_recovery/m21/q rom_0_timing_recovery_m21_reg/Q  -type DFF DFF
add mapped point rom_0/timing_recovery/x21/q rom_0_timing_recovery_x21_reg/Q  -type DFF DFF
add mapped point i4004/tio_board/L/q i4004_tio_board_L_reg/Q  -type DFF DFF
add mapped point i4004/tio_board/L/q i4004_tio_board_L_reg/QN  -type DFF DFF
add mapped point i4004/tio_board/timing_generator/m22/q i4004_tio_board_timing_generator_m22_reg/Q  -type DFF DFF
add mapped point i4004/tio_board/timing_generator/x12/q i4004_tio_board_timing_generator_x12_reg/Q  -type DFF DFF
add mapped point ram_0/ram_sel/q ram_0_ram_sel_reg/Q  -type DFF DFF
add mapped point ram_0/ram_sel/q ram_0_ram_sel_reg/QN  -type DFF DFF
add mapped point i4004/alu_board/acc[1]/q i4004_alu_board_acc_reg[1]/Q  -type DFF DFF
add mapped point i4004/alu_board/acc[1]/q i4004_alu_board_acc_reg[1]/QN  -type DFF DFF
add mapped point rom_0/timing_recovery/a12/q rom_0_timing_recovery_a12_reg/Q  -type DFF DFF
add mapped point rom_0/timing_recovery/a12/q rom_0_timing_recovery_a12_reg/QN  -type DFF DFF
add mapped point ram_0/io/q ram_0_io_reg/Q  -type DFF DFF
add mapped point ram_0/io/q ram_0_io_reg/QN  -type DFF DFF
add mapped point i4004/alu_board/acc_out[2]/q i4004_alu_board_acc_out_reg[2]/Q  -type DFF DFF
add mapped point i4004/alu_board/acc_out[2]/q i4004_alu_board_acc_out_reg[2]/QN  -type DFF DFF
add mapped point clockgen/clockdiv[2]/q clockgen_clockdiv_reg[2]/Q  -type DFF DFF
add mapped point clockgen/clockdiv[2]/q clockgen_clockdiv_reg[2]/QN  -type DFF DFF
add mapped point i4004/ip_board/row[1]/q i4004_ip_board_row_reg[1]/Q  -type DFF DFF
add mapped point i4004/ip_board/row[1]/q i4004_ip_board_row_reg[1]/QN  -type DFF DFF
add mapped point i4004/tio_board/timing_generator/a32/q i4004_tio_board_timing_generator_a32_reg/Q  -type DFF DFF
add mapped point i4004/tio_board/timing_generator/a32/q i4004_tio_board_timing_generator_a32_reg/QN  -type DFF DFF
add mapped point i4004/alu_board/acc_out[1]/q i4004_alu_board_acc_out_reg[1]/Q  -type DFF DFF
add mapped point i4004/alu_board/acc_out[1]/q i4004_alu_board_acc_out_reg[1]/QN  -type DFF DFF
add mapped point i4004/tio_board/timing_generator/a12/q i4004_tio_board_timing_generator_a12_reg/Q  -type DFF DFF
add mapped point i4004/tio_board/timing_generator/a12/q i4004_tio_board_timing_generator_a12_reg/QN  -type DFF DFF
add mapped point i4004/tio_board/timing_generator/a22/q i4004_tio_board_timing_generator_a22_reg/Q  -type DFF DFF
add mapped point i4004/tio_board/timing_generator/a22/q i4004_tio_board_timing_generator_a22_reg/QN  -type DFF DFF
add mapped point i4004/sp_board/row[2]/q i4004_sp_board_row_reg[2]/Q  -type DFF DFF
add mapped point i4004/sp_board/row[2]/q i4004_sp_board_row_reg[2]/QN  -type DFF DFF
add mapped point i4004/sp_board/row[1]/q i4004_sp_board_row_reg[1]/Q  -type DFF DFF
add mapped point i4004/sp_board/row[1]/q i4004_sp_board_row_reg[1]/QN  -type DFF DFF
add mapped point i4004/sp_board/row[0]/q i4004_sp_board_row_reg[0]/Q  -type DFF DFF
add mapped point i4004/sp_board/row[0]/q i4004_sp_board_row_reg[0]/QN  -type DFF DFF
add mapped point ram_0/opa[2]/q ram_0_opa_reg[2]/Q  -type DFF DFF
add mapped point ram_0/opa[2]/q ram_0_opa_reg[2]/QN  -type DFF DFF
add mapped point i4004/id_board/opa[1]/q i4004_id_board_opa_reg[1]/Q  -type DFF DFF
add mapped point i4004/id_board/opa[1]/q i4004_id_board_opa_reg[1]/QN  -type DFF DFF
add mapped point i4004/id_board/opr[0]/q i4004_id_board_opr_reg[0]/Q  -type DFF DFF
add mapped point i4004/id_board/opr[0]/q i4004_id_board_opr_reg[0]/QN  -type DFF DFF
add mapped point i4004/id_board/n0343/q i4004_id_board_n0343_reg/Q  -type DFF DFF
add mapped point i4004/id_board/n0343/q i4004_id_board_n0343_reg/QN  -type DFF DFF
add mapped point clockgen/clk1/q clockgen_clk1_reg/Q  -type DFF DFF
add mapped point clockgen/clk1/q clockgen_clk1_reg/QN  -type DFF DFF
add mapped point shiftreg/cp_delay[1]/q shiftreg_cp_delay_reg[1]/Q  -type DFF DFF
add mapped point shiftreg/cp_delay[1]/q shiftreg_cp_delay_reg[1]/QN  -type DFF DFF
add mapped point ram_0/rfsh_addr[3]/q ram_0_rfsh_addr_reg[3]/Q  -type DFF DFF
add mapped point ram_0/rfsh_addr[3]/q ram_0_rfsh_addr_reg[3]/QN  -type DFF DFF
add mapped point ram_0/opa[0]/q ram_0_opa_reg[0]/Q  -type DFF DFF
add mapped point ram_0/opa[0]/q ram_0_opa_reg[0]/QN  -type DFF DFF
add mapped point ram_0/rfsh_addr[0]/q ram_0_rfsh_addr_reg[0]/Q  -type DFF DFF
add mapped point ram_0/rfsh_addr[0]/q ram_0_rfsh_addr_reg[0]/QN  -type DFF DFF
add mapped point i4004/alu_board/acc_out[3]/q i4004_alu_board_acc_out_reg[3]/Q  -type DFF DFF
add mapped point i4004/alu_board/acc_out[3]/q i4004_alu_board_acc_out_reg[3]/QN  -type DFF DFF
add mapped point ram_0/rfsh_addr[2]/q ram_0_rfsh_addr_reg[2]/Q  -type DFF DFF
add mapped point ram_0/rfsh_addr[2]/q ram_0_rfsh_addr_reg[2]/QN  -type DFF DFF
add mapped point i4004/alu_board/cy_1/q i4004_alu_board_cy_1_reg/Q  -type DFF DFF
add mapped point i4004/alu_board/cy_1/q i4004_alu_board_cy_1_reg/QN  -type DFF DFF
add mapped point i4004/alu_board/acc_out[0]/q i4004_alu_board_acc_out_reg[0]/Q  -type DFF DFF
add mapped point i4004/alu_board/acc_out[0]/q i4004_alu_board_acc_out_reg[0]/QN  -type DFF DFF
add mapped point ram_0/reg_num[1]/q ram_0_reg_num_reg[1]/Q  -type DFF DFF
add mapped point ram_0/reg_num[1]/q ram_0_reg_num_reg[1]/QN  -type DFF DFF
add mapped point ram_0/reg_num[0]/q ram_0_reg_num_reg[0]/Q  -type DFF DFF
add mapped point ram_0/reg_num[0]/q ram_0_reg_num_reg[0]/QN  -type DFF DFF
add mapped point i4004/tio_board/timing_generator/x22/q i4004_tio_board_timing_generator_x22_reg/Q  -type DFF DFF
add mapped point i4004/tio_board/timing_generator/x22/q i4004_tio_board_timing_generator_x22_reg/QN  -type DFF DFF
add mapped point i4004/id_board/opr[1]/q i4004_id_board_opr_reg[1]/Q  -type DFF DFF
add mapped point i4004/id_board/opr[1]/q i4004_id_board_opr_reg[1]/QN  -type DFF DFF
add mapped point i4004/tio_board/timing_generator/x32/q i4004_tio_board_timing_generator_x32_reg/Q  -type DFF DFF
add mapped point i4004/tio_board/timing_generator/x32/q i4004_tio_board_timing_generator_x32_reg/QN  -type DFF DFF
add mapped point ram_0/timing_recovery/m22/q ram_0_timing_recovery_m22_reg/Q  -type DFF DFF
add mapped point ram_0/timing_recovery/m22/q ram_0_timing_recovery_m22_reg/QN  -type DFF DFF
add mapped point i4004/id_board/opa[3]/q i4004_id_board_opa_reg[3]/Q  -type DFF DFF
add mapped point i4004/id_board/opa[3]/q i4004_id_board_opa_reg[3]/QN  -type DFF DFF
add mapped point i4004/ip_board/row[0]/q i4004_ip_board_row_reg[0]/Q  -type DFF DFF
add mapped point i4004/ip_board/row[0]/q i4004_ip_board_row_reg[0]/QN  -type DFF DFF
add mapped point i4004/tio_board/poc/q i4004_tio_board_poc_reg/Q  -type DFF DFF
add mapped point i4004/tio_board/poc/q i4004_tio_board_poc_reg/QN  -type DFF DFF
add mapped point i4004/id_board/opa[0]/q i4004_id_board_opa_reg[0]/Q  -type DFF DFF
add mapped point i4004/id_board/opa[0]/q i4004_id_board_opa_reg[0]/QN  -type DFF DFF
add mapped point i4004/tio_board/timing_generator/m12/q i4004_tio_board_timing_generator_m12_reg/Q  -type DFF DFF
add mapped point i4004/tio_board/timing_generator/m12/q i4004_tio_board_timing_generator_m12_reg/QN  -type DFF DFF
add mapped point rom_1/n0128/q rom_1_n0128_reg/Q  -type DFF DFF
add mapped point rom_0/n0128/q rom_0_n0128_reg/Q  -type DFF DFF
add mapped point ram_0/rfsh_addr[1]/q ram_0_rfsh_addr_reg[1]/Q  -type DFF DFF
add mapped point ram_0/timing_recovery/m12/q ram_0_timing_recovery_m12_reg/Q  -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
